pipeline{
 agent any
 environment {
    ANYPOINT = credentials('ANYPOINT-LOCAL')
 }
 stages {
 	stage ('Build'){
 		steps {
 			
 				sh '/Users/gtalwadker/MuleSoft/apache-maven-3.6.0/bin/mvn -f cicdtestjenkins/pom.xml clean install'
 			
 		}
 	}
 	stage ('Deploy'){
 		steps {
 			
 				sh '/Users/gtalwadker/MuleSoft/apache-maven-3.6.0/bin/mvn -f cicdtestjenkins/pom.xml package deploy -Dusername=cicdservicesuser -Dpassword=Welcome1 -Denvironment=DEV -DmuleDeploy'
 		
 		}
 	}
 }

}