pipeline{
 agent any
 environment {
    ANYPOINT = credentials('ANYPOINT')
 }
 stages {
 	stage ('Build'){
 		steps {
 			
 				sh '/Users/gtalwadker/MuleSoft/apache-maven-3.6.0/bin/mvn -f cicdtestpub-jfrog/pom.xml clean install'
 			
 		}
 	}

 	
 	 		stage ('Publish Built Artifacts'){
 		steps {
 			
 				sh '/Users/gtalwadker/MuleSoft/apache-maven-3.6.0/bin/mvn -f cicdtestpub-jfrog/pom.xml package deploy'
 		
 		}
 	}
 }

}